---
- name: Hello Ansible - quick start

  hosts: localhost

  gather_facts: no

  tasks:
    - name: Hello server
      shell: date

    - uri:
        url: http://127.0.0.1:8000/todo/api/v1.0/Switches
        method: GET
        return_content: yes
      register: webpage

    - uri:
        url: http://127.0.0.1:8000/todo/api/v1.0/Switches
        method: POST
        return_content: yes
        body: "{{ lookup('file','body.json') }}"
        status_code: 201
        body_format: json
      register: webpage

