"""empty message

Revision ID: b8be9b0bdac8
Revises: 
Create Date: 2017-07-10 21:23:59.474243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8be9b0bdac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ports_Duplex'), 'ports', ['Duplex'], unique=False)
    op.create_index(op.f('ix_ports_Name'), 'ports', ['Name'], unique=False)
    op.create_index(op.f('ix_ports_Speed'), 'ports', ['Speed'], unique=False)
    op.create_index(op.f('ix_ports_Status'), 'ports', ['Status'], unique=False)
    op.drop_index('ix_ports_Duplex', table_name='ports')
    op.drop_index('ix_ports_Name', table_name='ports')
    op.drop_index('ix_ports_Speed', table_name='ports')
    op.drop_index('ix_ports_Status', table_name='ports')
    op.create_index(op.f('ix_switches_ManagementIP'), 'switches', ['ManagementIP'], unique=False)
    op.create_index(op.f('ix_switches_Name'), 'switches', ['Name'], unique=False)
    op.drop_index('ix_switches_ManagementIP', table_name='switches')
    op.drop_index('ix_switches_Name', table_name='switches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_switches_Name', 'switches', ['Name'], unique=False)
    op.create_index('ix_switches_ManagementIP', 'switches', ['ManagementIP'], unique=False)
    op.drop_index(op.f('ix_switches_Name'), table_name='switches')
    op.drop_index(op.f('ix_switches_ManagementIP'), table_name='switches')
    op.create_index('ix_ports_Status', 'ports', ['Status'], unique=False)
    op.create_index('ix_ports_Speed', 'ports', ['Speed'], unique=False)
    op.create_index('ix_ports_Name', 'ports', ['Name'], unique=False)
    op.create_index('ix_ports_Duplex', 'ports', ['Duplex'], unique=False)
    op.drop_index(op.f('ix_ports_Status'), table_name='ports')
    op.drop_index(op.f('ix_ports_Speed'), table_name='ports')
    op.drop_index(op.f('ix_ports_Name'), table_name='ports')
    op.drop_index(op.f('ix_ports_Duplex'), table_name='ports')
    # ### end Alembic commands ###
